BaseDir: ../KITTI-00/
KeyFrameDir: KeyFrames/
VOFile: slam_res/Twc.txt
LOFile: slam_res/floam_isam_00.txt
init_sim3: calib_res/he_rb_calib_00.txt
ORBVocabulary: ../data/Vocabulary/ORBvoc.txt
ORBConfig: ../config/orb_ori/KITTI00-02.yaml
VOIdFile: FrameId.yml
MapFile: Map.yml
ResFile: calib_res/ba_local_calib_00.txt
method: local # global or local
method_options: {"global":1,"local":2}