%YAML:1.0
---
io:
  BaseDir: ../KITTI-00/
  VOFile: slam_res/Twc.txt
  LOFile: slam_res/floam_isam_00.txt
  VOIdFile: FrameId.yml
  init_sim3: ../demo/sim3_demo_00.txt
  res_file: ../demo/sim3_res_00.txt
  PointCloudDir: ../data/00/velodyne
  PointCloudskip: 1
  precision: 6
  PointCloudOnlyPositiveX: true 
orb:
  Vocabulary: ../data/Vocabulary/ORBvoc.txt
  Config: ../config/orb_ori/KITTI00-02.yaml
  KeyFrameDir: ../KITTI-00/KeyFrames/
  MapFile: ../KITTI-00/Map.yml

runtime:
  max_pixel_dist: 1.5
  num_best_convis: 3 # set negative to use min_convis_weight
  min_covis_weight: 100
  min_rot_diff: 0.03
  kdtree2d_max_leaf_size: 10
  kdtree3d_max_leaf_size: 30
  corr_3d_2d_threshold: 40
  corr_3d_3d_threshold: 10
  norm_max_pts: 30
  norm_min_pts: 5
  norm_radius: 0.6
  norm_reg_threshold: 0.02  # 0.02
  min_diff_dist: 0.3 # 0.2
  he_threshold: 0.094
  err_weight: [1.0, 0.0]
  verborse: true
  use_plane: true  # set to false for the ablation study