%YAML:1.0
---
io:
  BaseDir: ../KITTI-02/
  VOFile: slam_res/Twc.txt
  LOFile: slam_res/floam_isam_02.txt
  VOIdFile: FrameId.yml
  ResFile: calib_res/iba_local_02.txt
  init_sim3: calib_res/iba_global_pl_02.txt
  PointCloudDir: ../data/02/velodyne
  PointCloudSkip: 1
  PointCloudOnlyPositiveX: true  # set to false to load points with negative X, or set true to save memory, provided you assume it is prior knowledge

orb:
  Vocabulary: ../data/Vocabulary/ORBvoc.txt
  Config: ../config/orb_ori/KITTI00-02.yaml
  KeyFrameDir: ../KITTI-02/KeyFrames/
  MapFile: ../KITTI-02/Map.yml

runtime:
  max_pixel_dist: 1.5
  num_best_convis: 5
  min_covis_weight: 200
  neigh_max_pts: 30
  neigh_min_pts: 5
  neigh_radius: 0.6
  norm_reg_threshold: 0.02
  min_diff_dist: 0.3
  init_sigma: 5
  init_l: 10
  pvalue: 3.
  min_eval: 0.01
  sigma_noise: 1.0E-10
  optimize_gpr: true
  kdtree2d_max_leaf_size: 10
  kdtree3d_max_leaf_size: 30
  max_iba_iter: 20
  inner_iba_iter: 10
  iba_min_diff: 1.0E-6
  sq_err_threshold: 500
  robust_kernel_delta: 5.0
  robust_kernel_3ddelta: 1.5
  err_weight: [1.0, 1.0]
  verborse: true
