%YAML:1.0
---
io:
  BaseDir: ../KITTI-02/
  VOFile: slam_res/Twc.txt
  LOFile: slam_res/floam_isam_02.txt
  VOIdFile: FrameId.yml
  ResFile: calib_res/iba_global_pl4_02.txt
  init_sim3: calib_res/he_lp_calib_02.txt
  gt_sim3: calib_res/gt_calib_02.txt
  PointCloudDir: ../data/02/velodyne
  PointCloudskip: 1
  PointCloudOnlyPositiveX: true 
orb:
  Vocabulary: ../data/Vocabulary/ORBvoc.txt
  Config: ../config/orb_ori/KITTI00-02.yaml
  KeyFrameDir: ../KITTI-02/KeyFrames/
  MapFile: ../KITTI-02/Map.yml

runtime:
  max_pixel_dist: 1.5
  num_best_convis: 3 # set negative to use min_convis_weight
  min_covis_weight: 200
  kdtree2d_max_leaf_size: 10
  kdtree3d_max_leaf_size: 30
  corr_3d_2d_threshold: 40
  corr_3d_3d_threshold: 10
  norm_max_pts: 30
  norm_min_pts: 5
  norm_radius: 0.6
  norm_reg_threshold: 0.02
  min_diff_dist: 0.2
  he_rot_threshold: 0.014
  he_tsl_threshold: 0.1255
  err_weight: [1.0, 1.0]
  init_frame: [0.1,0.1,0.1,0.3,0.3,0.3,1.0]  # [0.1,0.1,0.1,0.3,0.3,0.3,1.0]
  min_mesh: 1.0E-6
  lb: [-0.15,-0.15,-0.15,-0.3,-0.3,-0.3,-1.5]
  ub: [0.15,0.15,0.15,0.3,0.3,0.3,1.5]
  max_bbeval: 5000
  seed: 0
  use_vns: true
  use_cache: false
  cacheFile: ../KITTI-02/cache/cache_02_d1.5_fuse_wide.txt
  verborse: true
  use_plane: true  # set to false for the ablation study