BaseDir: ../KITTI-19/
KeyFrameDir: KeyFrames/
VOFile: slam_res/Twc.txt
LOFile: slam_res/floam_isam_19.txt
init_sim3: calib_res/he_rb_calib_19.txt
VOIdFile: FrameId.yml
ORBVocabulary: ../data/Vocabulary/ORBvoc.txt
ORBConfig: ../config/orb_ori/KITTI19.yaml
MapFile: Map.yml
ResFile: calib_res/ba_local_calib_19.txt
method: local # global or local
method_options: {"global":1,"local":2}