%YAML:1.0
---
BaseDir: ../KITTI-00/
KeyFrameDir: KeyFrames/
VOFile: slam_res/Twc.txt
LOFile: slam_res/floam_isam_00.txt
VOIdFile: FrameId.yml

VOIdFile: FrameId.yml
MapFile: Map.yml
ResFile: calib_res/ba_calib_00.txt
method: local # global or local
method_options: {"global":1,"local":2}