BaseDir: ../KITTI-07/
KeyFrameDir: KeyFrames/
VOFile: slam_res/Twc.txt
LOFile: slam_res/floam_isam_07.txt
init_sim3: calib_res/he_rb_calib_07.txt
VOIdFile: FrameId.yml
ORBVocabulary: ../data/Vocabulary/ORBvoc.txt
ORBConfig: ../config/orb_ori/KITTI04-12.yaml
MapFile: Map.yml
ResFile: calib_res/ba_global_calib_07.txt
method: global # global or local
method_options: {"global":1,"local":2}