%YAML:1.0
---
io:
  BaseDir: ../KITTI-07/
  VOFile: slam_res/Twc.txt
  LOFile: slam_res/floam_isam_07.txt
  VOIdFile: FrameId.yml
  ResFile: calib_res/iba_global_pl_07.txt
  init_sim3: calib_res/he_rb_calib_07.txt
  zero_translation: true
  gt_sim3: calib_res/gt_calib_07.txt
  PointCloudDir: ../data/07/velodyne
  PointCloudskip: 1
  PointCloudOnlyPositiveX: true 
orb:
  Vocabulary: ../data/Vocabulary/ORBvoc.txt
  Config: ../config/orb_ori/KITTI04-12.yaml
  KeyFrameDir: ../KITTI-07/KeyFrames/
  MapFile: ../KITTI-07/Map.yml

runtime:
  max_pixel_dist: 1.5
  num_min_corr2d_3d: 30
  num_best_covis: 3 # set negative to use min_covis_weight
  min_covis_weight: 100
  min_rot_diff: 0.03
  kdtree2d_max_leaf_size: 10
  kdtree3d_max_leaf_size: 30
  corr_3d_2d_threshold: 40
  corr_3d_3d_threshold: 10
  norm_max_pts: 30
  norm_min_pts: 5
  norm_radius: 0.6
  norm_reg_threshold: 0.01
  min_diff_dist: 0.2
  he_threshold: 0.142
  err_weight: [1.0, 1.0]
  init_frame: [0.5,0.5,0.5,0.5,0.5,0.5,0.5]
  min_mesh: 1.0E-6
  lb: [-0.1,-0.1,-0.1,-0.35,-0.3,-0.3,-1.0]
  ub: [0.1,0.1,0.1,0.35,0.3,0.3,1.0]
  max_bbeval: 5000
  valid_rate: 0.95
  seed: 0
  use_vns: true
  direction_type: N+1 QUAD
  use_cache: false
  cacheFile: ../KITTI-07/cache/cache_07_d1.5_fuse_wide.txt
  verborse: true
  use_plane: true  # set to false for the ablation study