%YAML:1.0
---
io:
  BaseDir: ../KITTI-03/
  VOFile: slam_res/Twc.txt
  LOFile: slam_res/floam_raw_03.txt
  VOIdFile: FrameId.yml
  ResFile: calib_res/iba_global_pl_03.txt
  init_sim3: calib_res/he_rb_calib_03.txt
  gt_sim3: calib_res/gt_calib_03.txt
  PointCloudDir: ../data/03/velodyne
  PointCloudskip: 1
  PointCloudOnlyPositiveX: true 
orb:
  Vocabulary: ../data/Vocabulary/ORBvoc.txt
  Config: ../config/orb_ori/KITTI03.yaml
  KeyFrameDir: ../KITTI-03/KeyFrames/
  MapFile: ../KITTI-03/Map.yml

runtime:
  max_pixel_dist: 1.5
  num_best_covis: 3 # set negative to use min_covis_weight
  min_covis_weight: 200
  kdtree2d_max_leaf_size: 10
  kdtree3d_max_leaf_size: 30
  corr_3d_2d_threshold: 40
  corr_3d_3d_threshold: 10
  norm_max_pts: 30
  norm_min_pts: 3
  norm_radius: 0.6
  norm_reg_threshold: 0.02
  min_diff_dist: 0.2
  he_threshold: 0.035
  err_weight: [1.0, 1.0]
  init_frame: [0.1,0.1,0.1,0.3,0.3,0.3,1.0]  # ratio of anisotropic maximum mesh
  min_mesh: 1.0E-6
  lb: [-0.1,-0.1,-0.1,-0.3,-0.3,-0.3,-1.0]
  ub: [0.1,0.1,0.1,0.3,0.3,0.3,1.0]
  max_bbeval: 5000
  valid_rate: 0.95
  seed: 0
  use_vns: true
  direction_type: N+1 QUAD
  use_cache: true
  cacheFile: ../KITTI-03/cache/cache_pl.txt
  verborse: true
  use_plane: true  # set to false for the ablation study