BaseDir: ../KITTI-05/
KeyFrameDir: KeyFrames/
VOFile: slam_res/Twc.txt
LOFile: slam_res/floam_isam_05.txt
init_sim3: calib_res/he_rb_calib_05.txt
VOIdFile: FrameId.yml
ORBVocabulary: ../data/Vocabulary/ORBvoc.txt
ORBConfig: ../config/orb_ori/KITTI04-12.yaml
MapFile: Map.yml
ResFile: calib_res/ba_local_calib_05.txt
method: local # global or local
method_options: {"global":1,"local":2}