%YAML:1.0
---
io:
  BaseDir: ../KITTI-05/
  VOFile: slam_res/Twc.txt
  LOFile: slam_res/floam_isam_05.txt
  VOIdFile: FrameId.yml
  ResFile: calib_res/he_calib_05.txt
  ResRBFile: calib_res/he_rb_calib_05.txt
  ResLPFile: calib_res/he_lp_calib_05.txt

runtime:
  zero_translation: true
  regulation: true
  robust_kernel_size: 0.15
  regulation_weight: 1.0E-3
  inner_iter: 10
  ex_iter: 20
  init_mu: 64
  divide_factor: 1.4
  min_mu: 0.01
  verborse: true
