%YAML:1.0
---
io:
  BaseDir: ../KITTI-00
  VOFile: slam_res/Twc.txt
  LOFile: slam_res/floam_isam_00.txt
  VOIdFile: slam_res/FrameId.yml
  ResFile: calib_res/iba_calib_00.txt
  init_sim3: calib_res/he_lp_calib_00.txt

orb:
  Vocabulary: ../data/Vocabulary/ORBvoc.txt
  Config: ../config/orb_ori/KITTI00-02.yaml
  KeyFrameDir: ../KITTI-00/KeyFrames/
  MapFile: ../KITTI-00/Map.xml

runtime:
  max_pixel_dist: 1.5
  kdtree2d_max_nn: 10
  kdtree3d_max_nn: 30
  norm_radius: 0.6
  max_iba_iter: 30
  verborse: true
