%YAML:1.0
---
io:
  BaseDir: ../KITTI-00/
  VOFile: slam_res/Twc.txt
  LOFile: slam_res/floam_isam_00.txt
  VOIdFile: FrameId.yml
  ResFile: calib_res/iba_global_pt_00.txt
  init_sim3: calib_res/he_calib_00.txt
  gt_sim3: calib_res/gt_calib_00.txt
  PointCloudDir: ../data/00/velodyne
  PointCloudskip: 1
  PointCloudOnlyPositiveX: true 
orb:
  Vocabulary: ../data/Vocabulary/ORBvoc.txt
  Config: ../config/orb_ori/KITTI00-02.yaml
  KeyFrameDir: ../KITTI-00/KeyFrames/
  MapFile: ../KITTI-00/Map.yml

runtime:
  max_pixel_dist: 1.5
  num_best_convis: 3 # set negative to use min_convis_weight
  min_covis_weight: 200
  kdtree2d_max_leaf_size: 10
  kdtree3d_max_leaf_size: 30
  corr_3d_2d_threshold: 40
  corr_3d_3d_threshold: 10
  norm_max_pts: 30
  norm_radius: 0.6
  norm_reg_threshold: 0.001
  min_diff_dist: 0.2
  he_threshold: 0.13
  err_weight: [1.0, 1.0]
  init_mesh: [0.1,0.1,0.1,0.3,0.3,0.3,1.0]
  min_mesh: 1.0E-8
  lb: [-0.1,-0.1,-0.1,-0.3,-0.3,-0.3,-1.0]
  ub: [0.1,0.1,0.1,0.3,0.3,0.3,1.0]
  max_bbeval: 2000
  seed: 0
  use_cache: false
  cacheFile: ../KITTI-00/cache/cache_00_d1.5_fuse_wide.txt
  verborse: true
  use_plane: true